---

- name: Service tasks
  become: true
  tags:
    - node_exporter_service
    - node_exporter
  block:

    - name: Load systemd default options 
      ansible.builtin.set_fact:
        node_exporter_systemd_default_parsed: "{{ node_exporter_systemd_default | from_yaml }}"

    - name: Merge systemd options
      ansible.builtin.set_fact:
        node_exporter_systemd_options_merged: >-
          {{ 
            node_exporter_systemd_default_parsed
            | combine(
              { 'Service': {
                  'ExecStart': ('/opt/node_exporter/node_exporter $ARGS' if node_exporter_install_source == 'binary' else '/usr/bin/prometheus-node-exporter $ARGS')
              }},
              recursive=True
              )
            | combine(node_exporter_systemd_options, recursive=True)
          }}

    - name: Debug variables
      when: node_exporter_debug | bool
      ansible.builtin.include_tasks: debug/service.yml

    - name: Manage node_exporter systemd unit
      when:
        - (node_exporter_systemd_options is defined and node_exporter_systemd_options | length > 0)
          or node_exporter_install_source == 'binary'
      ansible.builtin.template:
        src: node-exporter.service.j2
        dest: "/etc/systemd/system/{{ node_exporter_service_name }}"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Reload systemd daemon
        - Restart node-exporter

    - name: Manage node_exporter service
      ansible.builtin.service:
        name: "{{ node_exporter_service_name }}"
        state: "{{ node_exporter_service_ensure }}"
        enabled: "{{ node_exporter_service_enable }}"
      when: not ansible_check_mode
